### ISSUE TITLE
Supporting other header parameters

### ISSUE THREAD

**Issue by ctoomey** [jwt-scala/jwt-scala#103]
First off, thanks for creating and open-sourcing this library! It's exactly the kind of library I was hoping to find as my team is starting to use JWTs.

Looking around, I saw that `JwtHeader` only supports a limited set of parameters. Given there are many other [registered parameters for JWS](https://tools.ietf.org/html/rfc7515#section-4.1)/JWE, not to mention custom parameters, and that you have `JwtClaim` as a great example of how to make it extensible, I'm curious if there's a particular reason why it isn't, or it just hasn't been needed yet?

In my case we're planning to use the `x5u` parameter to refer to the URL from which to get the X.509 certificate so I already need this.

**Comment by pauldijou** [comment]
Sorry for the delay, I don't spend much time on Scala anymore.

It mostly hasn't been needed yet indeed. I've tried to keep the header as small, simple and typed as possible. People should know what they are doing but I would be concerned that they might override important keys (like the `alg` one) if allowed to put whatever they want into the header.

Feel free to open a PR to add the `x5u` key if you need it. If you think dynamic keys should be supported, I don't mind merging that too.

**Comment by ctoomey** [comment]
Thanks, makes sense. Turns out we're going to use the `kid` param instead of `x5u` so don't need any changes for now.
