### ISSUE TITLE
Argonaut support

### ISSUE THREAD

**Issue by bodand** [jwt-scala/jwt-scala#105]
Having support for [Argonaut](http://argonaut.io/) JSON library by the Scalaz people would be great. Is it possible in the near future, just later, or even never?

**Comment by pauldijou** [comment]
I won't do it myself but I'm fine reviewing, merging and publishing any pull request with tests. You can take a look at how other libs do it (there are only 3 or 4 files most of the time, and only one really has code).

**Comment by bodand** [comment]
Okay, will look into it, but right now with Christmas coming and all I don't have much time so don't have to expect it too soon.

**Comment by bodand** [comment]
Created a PR, the code itself works, but had a bit of trouble with the docs, especially check if those work, because I don't really know how they are supposed to.

**Comment by pauldijou** [comment]
It has been released.
