### ISSUE TITLE
`toJson` method is misleading

### ISSUE THREAD

**Issue by adamkasztenny** [jwt-scala/jwt-scala#109]
In additional to the usual fields, my JWT token had an extra field in the JSON:
```json
{
  "extraField": "...",
  "iss": "...",
  "sub": "...",
  "aud":  "...",
  "iat":  "...",
  "exp":  "..."
}
```
I was debugging and I got a `JwtClaim` back. I called `toJson` on it but it only showed the standard JWT fields. What I realized later is that `content` had the extra field.

It would be nice to have an option to pass in a custom case class to the `decode` method which can have extra fields. Or a simple map in the `JwtClaim` class which has extra fields.

**Comment by pauldijou** [comment]
I'm not sure to fully understand it. `toJson` should give you the exact object you mentioned. It merges the standard fields into the `content` field. `content` is only on the `JwtClaim` class, it should never show in the JSON side.

Are you using any JSON lib? Pure Scala is intended to be very low level without any idea how to actually parse JSON. If you are using a JSON lib, they all have a method `decodeJson` which will give you your extra fields as a JSON object (which is nearly a map).

**Comment by adamkasztenny** [comment]
Yes, I am using a JSON lib. I'm able to decode the extra fields from `content`. I can try debugging again and see if the extra fields are there, maybe I was using the wrong JWT while debugging the first time.

**Comment by adamkasztenny** [comment]
Ah, I see: 
```scala
  def toJson: String = JwtUtils.mergeJson(JwtUtils.hashToJson(Seq(
    "iss" -> issuer,
    "sub" -> subject,
    "aud" -> audience,
    "exp" -> expiration,
    "nbf" -> notBefore,
    "iat" -> issuedAt,
    "jti" -> jwtId
  ).collect {
    case (key, Some(value)) => (key -> value)
}), content)
```
The standard fields are merged with content. I must be wrong in that case. Thanks for the response.
