### ISSUE TITLE
Circe support

### ISSUE THREAD

**Issue by alari** [jwt-scala/jwt-scala#11]
It would be great to have circe json support

https://github.com/travisbrown/circe

**Comment by pauldijou** [comment]
Got it, will try to find some time next week.

**Comment by dwhitney** [comment]
Hi, I've got an initial implementation here: https://github.com/dwhitney/jwt-scala
I'll update the docs tonight after work and submit a pull request

**Comment by alari** [comment]
Thanks! :)

**Comment by alari** [comment]
BTW, when will it appear in Maven Central?

**Comment by pauldijou** [comment]
Hopefully by the end of the week, I'm still working on other features before releasing.

**Comment by dwhitney** [comment]
Thank you!

**Comment by pauldijou** [comment]
Released. Should hit Maven in the next 24h. Enjoy and happy new year.
