### ISSUE TITLE
Decode expired token

### ISSUE THREAD

**Issue by marius-carp** [jwt-scala/jwt-scala#12]
Hi, I have a question regarding decoding expired tokens. Is it possible to decode an expired token?

This is the token 

``` sh
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIbWFjU0hBMjU2In0.eyJleHAiOjE0NTAyNzUyNzIsInVzZXIiOnsiaWRVc2VyIjo4Nzc3MywiaWRDb25jZXB0VXNlciI6NTgxMSwiZmlyc3ROYW1lIjoiRnJ1bnphIiwibGFzdE5hbWUiOiJMZWFmIiwiZW1haWwiOiJmcnVuemFAYXNzaXN0LnJvIn19.4um3Q2IuyXWMaohwUF5_fAiVdrIlen68Oqs2CLLLVlY
```

I can decode the token using http://jwt.io I am able to see the payload, without specifying any secret key.

``` json
{
  "exp": 1450275272,
  "user": {
    "idUser": 87773,
    "firstName": "Frunza",
    "lastName": "Leaf",
    "email": "frunza@assist.ro"
  }
}
```

Thanks,
Marius

**Comment by pauldijou** [comment]
Indeed, there is no way to do that currently, all decoding methods also validate the token since you should trash all invalid tokens anyway. Is there a good reason to read such tokens? I don't really like adding methods that people shouldn't use.

**Comment by marius-carp** [comment]
@pauldijou Thanks for the quick response!

I have some desktop apps (Desktop-App) that need to login using my application (Auth-App), but those desktop apps don't call directly to Auth App, they go thought a middleware-application (Middle-App - does a lot of things). So when a user submits his credentials to the Middle-App, the Middle-Apps calls Auth-App and gets an JWT token that has 5 min exiration time (also puts some data in payload, and adds user data in Redis Cache, so we can identify the user later, the maxAge of user session in Auth-App is 30 days, after this date the user has to relog), this token is sent back to the client (Desktop-App) through Middle-App as I said earlier. 

Now the user can make calls to to Middle-App (authorized calls) for the next 5 minutes, after those 5 minutes the token expires, and it needs to be refreshed. So the Middle-App needs to call the Auth-App with an expired token. 

I have to decode the expired token, get some date from the payload and match the redis data, if the date matches I refresh user's token else I redirect the user to login page.

If you have a better idea please advise me!

**Comment by pauldijou** [comment]
I understand. Sounds legit and I don't have any better solution.

It's quite easy to implement but I'm not sure how to impact the current API : adding an optional parameter to disable verification or adding new methods. There are already quite a lot of methods so maybe the 1st solution. Any thoughts?

PS: just wandering, if someone stole a token (a 5min one), what prevent him from refreshing it after expiration date? Do you have bonus security in the middle app?

**Comment by marius-carp** [comment]
I have not yet thought of this, but I have something in mind. I will share with you as soon as I will implement it. 

Regarding decoding expired tokens I followed some of library's code and managed to decode the token, by writing a few methods.

**Comment by pauldijou** [comment]
0.5.0 has been released and you can now set a final `JwtOptions` that let you disable validation checks when decoding. This should do the job for you. Read the doc for more info.

**Comment by marius-carp** [comment]
Thank you!
