### ISSUE TITLE
Support for Scala 2.13.0-RC2

### ISSUE THREAD

**Issue by ennru** [jwt-scala/jwt-scala#124]
Would be great!

**Comment by pauldijou** [comment]
Not sure why, but looks like only Play 2.8.0-M1 has been compiled to Scala 2.13.0.RC2 not not Play 2.7.2. I guess we will have to wait to them to release it. And probably target either RC3 or 2.13.0 directly depending on how fast they do it.

**Comment by ennru** [comment]
The RCs came a bit quick. Scala 2.13.0 has been published now, Akka and Play will follow as soon as Scalatest arrives.

**Comment by pauldijou** [comment]
This is done in 3.0.1 (except for `play`. `play-json` is ok).

**Comment by ennru** [comment]
Thank you!
