### ISSUE TITLE
java.security.NoSuchAlgorithmException: ECDSA KeyFactory not available

### ISSUE THREAD

**Issue by xmeng1** [jwt-scala/jwt-scala#131]
The new version >3.0.0, get the error :+1: 

java.security.NoSuchAlgorithmException: ECDSA KeyFactory not available

It seems the Java Security package does not contain the ECDSA algorithm.

**Comment by brakthehack** [comment]
This is intended. You need to add the BouncyCastle library to your application and call:
```
Security.addProvider(new BouncyCastleProvider)
```

**Comment by pauldijou** [comment]
Thanks for raising the issue, I added some documentation to the [3.0.0 release](https://github.com/pauldijou/jwt-scala/releases/tag/v3.0.0). Should have done it from the start, my bad.

**Comment by xmeng1** [comment]
got it ~
