### ISSUE TITLE
Audience is defined as Set and serialized as such even when audience is singular

### ISSUE THREAD

**Issue by msinton** [jwt-scala/jwt-scala#132]
This is incompatible with some APIs.

Namely, Google's OAuth API - Cloud Identity-Aware Proxy (IAP)
https://cloud.google.com/iap/docs/authentication-howto#iap_make_request-java

When generating a token with jwt-scala google responds with:

> {
  "error": "invalid_grant",
  "error_description": "Invalid JWT: Failed audience check. The right audience is https://www.googleapis.com/oauth2/v4/token"
}

The workaround is to set the audience manually within the content:
`claim.withContent("\"aud\": \"<insert_audience_here>\"")`

**Comment by pauldijou** [comment]
Released in 3.1.0
