### ISSUE TITLE
Question about JWK files with multiple keys

### ISSUE THREAD

**Issue by thomhickey** [jwt-scala/jwt-scala#134]
Hello and thank you for your great work! Cryptography makes me want to cry, I'm so glad you put in the effort here.

I have a question about using jwt-scala to verify JWTs from AWS Cognito. I'm following this guide:

https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html

It says I should decode the id token (a jwt), then check the kid to know which of the two public keys (Cognito user pools use an RSA key pair) I should use to verify the signature of the token. But isn't that a chicken-and-egg situation? Don't I already need to have used the public key to decode the token in step 1? So I've resorted to:

```
      if (JwtUpickle.isValid(idToken, config.getString("cognitoPublicKey1"), Seq(JwtAlgorithm.RS256)) ||
        JwtUpickle.isValid(idToken, config.getString("cognitoPublicKey2"), Seq(JwtAlgorithm.RS256))) {
```

Which doesn't make me want to shoot myself, but it's close. So far this is working and is allowing me to:

a) authenticate a Vue.js SPA using purely front-end (AWS Amplify/Cognito)
b) after login, proxy API requests to an external API from Vue -> Scala -> API -> Scala -> Vue using CSRF tokens + JWT verification.
c) not expose api tokens to the front-end but also not manage session state on the back-end
d) sleep at night (see c) above)

Or am I nuts?

Thanks so much,
-Thom

**Comment by pauldijou** [comment]
A JWT token is not encrypted or anything, it's just the raw JSON with a signature at the end to ensure content was not tampered. You could split the token (it's `[header].[claim].[signature]`), parse the header to get the `kid`, and then check if valid. I haven't written Scala in years, so that's pseudo code:

```scala
var rawHeader = token.split('.').head;
var header = upickle.parse(rawHeader);
var key = if (header.kid == "something") "cognitoPublicKey1" else "cognitoPublicKey2";
var isValid = JwtUpickle.isValid(idToken, config.getString(key), Seq(JwtAlgorithm.RS256));
```

**Comment by thomhickey** [comment]
Thanks so much, and sorry for not seeing your reply earlier! .... so the only encrypted portion of the toke is the value? They all looked encrypted to me, but maybe that's because Cognito uses hashes for everything.

**Comment by pauldijou** [comment]
Sorry, went a little fast. They are base64 encoded but you can decode that freely.

**Comment by thomhickey** [comment]
Got it ... sorry I should have read up more on the internals of JWT. Thanks for your time, Paul.
