### ISSUE TITLE
jwt-core does not parse entire header (3.1.0)

### ISSUE THREAD

**Issue by kalexmills** [jwt-scala/jwt-scala#136]
The present definition of the core library only extracts the algorithm from the JWT header (JwtPureScala:82), despite the remaining fields being present in the JwtHeader case class. This was quite an unexpected feature.

The other implementations appear to parse the entire header correctly, so I'll move over to one of those for now.

**Comment by kalexmills** [comment]
Looks like JwtCirce also uses the implementation from JwtCore, unless you explicitly use 'decodeJsonAll', so this would appear to also affect other variant libs.

**Comment by pauldijou** [comment]
It is true for `JwtPureScala` but, as stated in the file, this is more for demo / testing purposes rather than production one since there is no native way to correctly parse a JSON string in Scala.

`JwtCore` should no rely on `JwtPureScala` at all so `JwtCirce` should be fine.
