### ISSUE TITLE
jwt-play not supporting for scala 2.13

### ISSUE THREAD

**Issue by raja-shekar** [jwt-scala/jwt-scala#137]
Maven repo doesn't have scala 2.13 jar for jwt-play

**Comment by pauldijou** [comment]
Where are you looking? I can see all builds for `2.13` here https://repo.maven.apache.org/maven2/com/pauldijou/

Here are the released versions for `2.13` for `jwt-core`: https://repo.maven.apache.org/maven2/com/pauldijou/jwt-core_2.13/

**Comment by raja-shekar** [comment]
> Where are you looking? I can see all builds for `2.13` here https://repo.maven.apache.org/maven2/com/pauldijou/
Here I found only

jwt-play_2.10/
jwt-play_2.11/      
jwt-play_2.12/       

Not able to see jwt-play_2.13

**Comment by pauldijou** [comment]
Oh, my bad, I misread it was `jwt-play` specifically. The reason it's missing is because last time I published, `Play` framework did not support Scala 2.13. Do you know if this has changed?

**Comment by raja-shekar** [comment]
Yes. Play supports for scala 2.13.

**Comment by pauldijou** [comment]
Released in 4.0.0
