### ISSUE TITLE
Feature suggestion: utility for extracting an RS256 public key from a X.509 certificate

### ISSUE THREAD

**Issue by PiotrJander** [jwt-scala/jwt-scala#139]
I was using an identity provider (KeyCloak) which exposed its X.509 certificate, but not its RS256 public key directly.

I had to write this function, which extracts a Base64-encoded public key from a Base64-encoded certificate.

```scala
import java.io.ByteArrayInputStream
import java.security.cert.{CertificateFactory, X509Certificate}
import java.util.Base64

object RSAKeyUtils {
  def getRSAPublicKeyFromX509Certificate(certificateString: String): String = {
    val certificateFactory = CertificateFactory.getInstance("X.509")
    val certificate = certificateFactory
      .generateCertificate(
        new ByteArrayInputStream(certificateString.getBytes())
      )
      .asInstanceOf[X509Certificate]
    Base64.getEncoder.encodeToString(certificate.getPublicKey.getEncoded)
  }
}
```

Given that this is a common use case when working with JWT tokens, would this utility function be accepted if I made a PR with it?

**Comment by pauldijou** [comment]
Sure. There is a `JwtUtils` file for this kind of stuff. Reusing `JwtBase64` would be nice too.
