### ISSUE TITLE
Decode, but ignore signature

### ISSUE THREAD

**Issue by HopefulLlama** [jwt-scala/jwt-scala#141]
Currently, if there is a signature on the JWT, and you **do not** pass a key, and an algorithm, you receive a `Failure` such as:

```
pdi.jwt.exceptions.JwtNonEmptySignatureException: Non-empty signature found inside the token while trying to verify without a key.
```

It would be nice to be able to decode the JWT, while ignoring the verification of the signature, and continue with the decoded header and claims part of the JWT. 

This is mostly for debugging or testing purposes, rather than for use in production.

**Comment by pauldijou** [comment]
Check the `signature` property from the possible [options](https://jwt-scala.github.io/jwt-scala/jwt-core-jwt.html#options).

Alternatively, you could split your token at the 1st dot from the end and remove the signature.

**Comment by HopefulLlama** [comment]
Thank you! Using the `signature` option is exactly what I was looking for.

**Comment by agaal** [comment]
Hi,

can you please share the solution again?
The link does not work anymore.

**Comment by pauldijou** [comment]
@agaal Something like `Jwt.decode(token, JwtOptions(signature = false))`.

More at https://jwt-scala.github.io/jwt-scala/jwt-core-jwt.html#options
