### ISSUE TITLE
Add support for verifying Firebase ID tokens?

### ISSUE THREAD

**Issue by marko-asplund** [jwt-scala/jwt-scala#143]
I'm using `jwt-scala` to verify Firebase ID tokens as described in
https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library

In summary a couple of things I've had to implement for this:
* load token signing certificates from a set of URLs
* verify tokens based on the signing certificate ID (key ID) identified in the token
* periodically update certificates

Is this a feature that the `jwt-scala` user community would be interested in?
I've a prototype implementation that I would be willing to contribute if deemed feasible:
https://github.com/marko-asplund/jwt-token-validator

AFAIK, this could be useful for verifying ID tokens from other providers as well and probably could be made more generic.

**Comment by pauldijou** [comment]
The feature sounds nice but I will pass. The main reason is that I don't do Scala anymore and I barely have time to maintain this project so there is no plan to add  any new big feature to it. You can build it and publish it to Maven though. If you do so, I can include a link to it in the README or something.
