### ISSUE TITLE
JWT ECSDA - used private key instead of public and public instead of private

### ISSUE THREAD

**Issue by sim732** [jwt-scala/jwt-scala#145]
Usage

scala> val token = Jwt.encode("""{"user":1}""", ecKey.getPrivate, JwtAlgorithm.ES512)
token: String = eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9.eyJ1c2VyIjoxfQ.AS8XjhcOx8L4wtDgcnHZt2e4UueqlCSmT_d6EiHAnUZTclFc62QPbcKO8ikz_HJXN-Lhi5fN3JUv0ZC3xGOvR2-NAbv7hZdYxQocBugXouLL7Ryn2P21IEDdi4EjOu19kPdp9cfN15XNGRV5VpIVBQ1n4-VVDiWpByy0r8yhrhC_bHsn

scala> Jwt.decode(token, ecKey.getPublic, JwtAlgorithm.allECDSA)
res7: scala.util.Try[pdi.jwt.JwtClaim] = Success(pdi.jwt.JwtClaim@a0b74282)

public key for encode and private key for decode

**Comment by pauldijou** [comment]
Are you sure about this @sim732 ? Do you have any reference? 

According to [the spec](https://tools.ietf.org/id/draft-jones-json-web-token-01.html#DefiningECDSA)

> A JWT is signed with an ECDSA P-256 SHA-256 signature as follows:
>
> - Generate a digital signature of the UTF-8 representation of the JWT Signing Input using **ECDSA P-256 SHA-256 with the desired private key**. The output will be the EC point (R, S), where R and S are unsigned integers.
> - Turn R and S into byte arrays in big endian order. Each array will be 32 bytes long.
> - Concatenate the two byte arrays in the order R and then S.
> - Base64url encode the 64 byte array as defined in this specification.

So this is encoding using the private key. And then:

> The following procedure is used to validate the ECDSA signature of a JWT:
>
> - Take the JWT Crypto Segment and base64url decode it into a byte array. If decoding fails, the token MUST be rejected.
> - The output of the base64url decoding MUST be a 64 byte array.
> - Split the 64 byte array into two 32 byte arrays. The first array will be R and the second S. Remember that the byte arrays are in big endian byte order; please check the ECDSA validator in use to see what byte order it requires.
> - Submit the UTF-8 representation of the JWT Signing Input, R, S **and the public key (x, y) to the ECDSA P-256 SHA-256 validator**.
> - If the validation fails, the token MUST be rejected.

The public key for the decoding and validation.
