### ISSUE TITLE
Audience Always `None`

### ISSUE THREAD

**Issue by mazurio** [jwt-scala/jwt-scala#147]
Hello 👋 ,

I am trying to extract `audience` from `JwtClaim` in order to assert value in some test cases. I have run into the issue where `audience` (and `id` too actually) always return `None`.

Is there anything I am missing or is this a bug?

```scala
import java.time.Clock

import pdi.jwt._

implicit val clock: Clock = Clock.systemUTC()

val claim = JwtClaim(
  issuer = Some("issuer"),
  subject = Some("subject"),
  audience = Some(Set("audience"))
).withContent("""{}""")

val secretKey = "test"

val token = Jwt.encode(claim, secretKey, JwtAlgorithm.HS512)

val raw = Jwt.decodeRaw(token, secretKey, Seq(JwtAlgorithm.HS512))

println(raw)

val decoded =
  Jwt.decode(token, secretKey, Seq(JwtAlgorithm.HS512))

println(decoded.get.audience)
```

<img width="1511" alt="Screen Shot 2019-10-18 at 15 39 27" src="https://user-images.githubusercontent.com/6534301/67103666-7ffe5c80-f1bd-11e9-9f8d-3251cde0c6aa.png">

Might be worth adding that:
```scala
println(decoded.get.issuer)
println(decoded.get.audience)
```

returns:

```
Some(issuer)
None
```

**Comment by pauldijou** [comment]
It looks like you are not using a JSON library. The [pure Scala implementation](https://github.com/pauldijou/jwt-scala/blob/master/core/src/main/scala/JwtPureScala.scala#L6-L10) as some severe limitations as I am not planning to re-do a JSON library. Could you try to use one?

**Comment by mazurio** [comment]
@pauldijou Makes sense! Thanks for quick reply.
