### ISSUE TITLE
Upgrade to the newest version of Bouncy Castle Crypto Package

### ISSUE THREAD

**Issue by damianbl** [jwt-scala/jwt-scala#152]
Currently jwt-scala depends on 
`org.bouncycastle:bcpkix-jdk15on:1.60`
I suggest upgrading to
`org.bouncycastle:bcpkix-jdk15on:1.64`

Reason:
there is a bug causing a lot of warnings:
`WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/usr/local/lib/org.bouncycastle.bcprov-jdk15on-1.60.jar) to constructor sun.security.provider.Sun()
`

It is fixed in version 1.64.

If the idea is approved I can prepare a PR.

**Comment by pauldijou** [comment]
Sure, that makes sense. I won't be able to release for at least 2 weeks so no rush :-)
