### ISSUE TITLE
Failure to correctly parse valid `sub` claims.

### ISSUE THREAD

**Issue by umatrangolo** [jwt-scala/jwt-scala#161]
Failure to correctly parse valid `sub` claims.

I happen to have a system that uses signed longs as ids and sometimes we have users/resources having negative ones. Trying to use JWT tokens with a negative id results in `JWT.decode()` to miss the `sub` (and potentially others claims).

On my REPL:

```
scala> val jwtClaim = Jwt.decode(Jwt.encode(JwtClaim(subject = Some("-3639903027111337383")), secret, HS384), secret, Seq(HS384)).get
jwtClaim: pdi.jwt.JwtClaim = pdi.jwt.JwtClaim@b0b7793

scala> jwtClaim.toJson
res30: String = {"sub":"-3639903027111337383"}

scala> jwtClaim.subject
res31: Option[String] = None

scala> jwtClaim.content
res32: String = {"sub":"-3639903027111337383"}
```

AFAIK `"-3639903027111337383"` is a valid `sub` value as per [RFC](https://tools.ietf.org/html/rfc7519#section-4.1.2).

The cause is the regex being used in the decoding phase that does not  match on the `-`.

The code is https://github.com/pauldijou/jwt-scala/blob/88604833f4da474679db2617c7ffc67815b7dfe9/core/src/main/scala/JwtPureScala.scala#L33

**Comment by umatrangolo** [comment]
The workaround is to use any of JWT json based decoder:

```JwtSprayJson.decode()```

This will correctly extract the `sub` from the JWT token.

**Comment by pauldijou** [comment]
That's the way to go. The pure Scala implementation will never be a proper JSON parser, it's too much work and plenty of good solutions are already available.

**Comment by pauldijou** [comment]
(as a side node, feel free to submit a pull request to fix your use-case if you want, but I would still recommend using a proper JSON library anyway)
