### ISSUE TITLE
java.lang.NoSuchMethodError: play.api.Mode$.Dev()Lscala/Enumeration$Value

### ISSUE THREAD

**Issue by Mechstud** [jwt-scala/jwt-scala#163]
Hi,

My Scala version is: **2.11.7**

Added the following dependencies:
```
"com.pauldijou" %% "jwt-play-legacy" % "0.7.0",
"com.pauldijou" %% "jwt-play" % "0.14.0",
"com.pauldijou" %% "jwt-core" % "0.5.1",
"com.auth0" % "jwks-rsa" % "0.6.1"
```

However, while trying to compile, getting the following error:

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> java.lang.NoSuchMethodError: play.api.Mode$.Dev()Lscala/Enumeration$Value;
> 	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:88)

Kindly assist. Been stuck for too long!!

**Comment by pauldijou** [comment]
I tried to understand a bit but I gave up. I haven't done any Scala in years, I can barely maintain that lib currently. The version you are using is quite old sadly, not sure if you can use a more recent one.
