### ISSUE TITLE
Performance of String.split() is poor, use a more performant method

### ISSUE THREAD

**Issue by jfosback** [jwt-scala/jwt-scala#164]
https://github.com/pauldijou/jwt-scala/blob/88604833f4da474679db2617c7ffc67815b7dfe9/core/src/main/scala/Jwt.scala#L185

I did some timing of this, and the performance of split() is abysmal.  Here's a simple split function that's orders of magnitude faster than Java's regex split:

```
  // This is much faster than String.split()
  private def splitString(input: String, separator: Char): Array[String] = {
    val builder = scala.collection.mutable.ArrayBuffer.empty[String]
    var lastIndex = 0
    var index = input.indexOf(separator, lastIndex)
    while (index != -1) {
      builder.addOne(input.substring(lastIndex, index))
      lastIndex = index + 1
      index = input.indexOf(separator, lastIndex)
    }
    // Add the remainder
    builder.addOne(input.substring(lastIndex, input.length))
    builder.toArray
  }
```
Here's a link to a nice performance analysis of alternates for String.split():

http://demeranville.com/battle-of-the-tokenizers-delimited-text-parser-performance/

For applications making heavy use of JWT tokens for every web service call, the difference can really add up.

**Comment by pauldijou** [comment]
Thanks for sharing that. Unfortunately, I don't think I will be able to work on that project until at least August. Hope I won't forget.

**Comment by erwan** [comment]
Is there really cases for JWT where it makes a difference?

I can understand if you split a very long string, but JWT token are usually not that long so does it matter with the current use case?

**Comment by pauldijou** [comment]
Probably not that much...

That said, even if the performance gain is always nice, my main reason to get rid of `split` is because I consider it a bit of a broken api that I never liked using.

```scala
"aaaaaaaaaa".split("a");
// return an empty array
```

This makes no sense to me. How can splitting a 10 characters long string result in an empty array? How do you differenciate between `"aa".split("a");` and `"aaaaaaaaaa".split("a");`?

**Comment by pauldijou** [comment]
Improved in 5.0.0
