### ISSUE TITLE
the request content was malformed: in postman 

### ISSUE THREAD

**Issue by nd10299** [jwt-scala/jwt-scala#166]
![Screenshot (70)](https://user-images.githubusercontent.com/41955529/92258444-7de7de00-eef4-11ea-866a-28d80a06f8a6.png)
![Screenshot (72)](https://user-images.githubusercontent.com/41955529/92258450-8213fb80-eef4-11ea-95dd-02eee1cb93cf.png)
![Screenshot (73)](https://user-images.githubusercontent.com/41955529/92258457-83ddbf00-eef4-11ea-9459-a1473f8311e2.png)
![Screenshot (74)](https://user-images.githubusercontent.com/41955529/92258466-86d8af80-eef4-11ea-9c45-d1c238b8b5e9.png)

so im doing some basic jwt and generating token but using spray json  and when i run this in my postman error occurred and it shows -400  bad request-the request content was malformed ... please help me out

**Comment by pauldijou** [comment]
JWT are using a specific HTTP header but it seems you are trying to use `Basic Auth` on your Postman request, which is totally different. You should send a proper JWT token, base64 encoded, in the correct header. I encourage you to read more how those tokens are used in an HTTP request.

**Comment by nd10299** [comment]
ok got it
