### ISSUE TITLE
Allow decoders to accept a Base64 URL encoded String parameter

### ISSUE THREAD

**Issue by rschanafelt** [jwt-scala/jwt-scala#17]
It would be a very nice convenience to be able to pass in a Base64 URLEncoded String as a parameter to the **decode()** methods--as this is what is often used for secrets with authentication services.

The workaround for now is to manually decode the secret and then construct a new SecretKey with the byte array and the algorithm. Unfortuntely, it's a bit redundant to have to go that way since we specify the algorithm(s) in the decoder anyway.

For example, instead of this:

``` scala
val decodedSecretByteArray = Base64.getUrlDecoder.decode(base64Secret)
Jwt.decode(token, new SecretKeySpec(decodedSecretByteArray, "HmacSHA256"), JwtAlgorithm.allHmac())
```

We could just do this:

``` scala
Jwt.decode(token, base64Secret, JwtAlgorithm.allHmac())
```

Would you consider adding this capability? Or am I missing something that would make this easier?

**Comment by pauldijou** [comment]
Not sure I understand the problem. Why would your secret key be Base64 encoded? It's only on your server, isn't a normal string enough?

Even if the signature did accept a Base64 key, it would only decode it (the `val decodedSecretByteArray = Base64.getUrlDecoder.decode(base64Secret)` line) but there is no way to automatically create the SecretKey since we don't know which algorithm to use, `JwtAlgorithm.allHmac()` is a sequence of algorithms after all.

**Comment by rschanafelt** [comment]
The secret key I receive from our Authentication/Identity provider is Base64 URL encoded, and that's something I have no control over. I agree that a normal string is fine if you have control over it, unfortunately that's not what I'm dealing with.

Ah, I do see your point about knowing which algorithm, as the sequence is the list of algorithms accepted by the decoder rather than specifying which one encoded the token. I guess I was assuming the decoder would try all the algorithms in the sequence to find one that worked.

Nevertheless, I think you've answered my question here--as there's really not another good way to handle it. So feel free to close this issue.

By the way, thanks for creating and maintaining this library, I really appreciate your contributions to open-source and your responsiveness!

**Comment by pauldijou** [comment]
Thanks for those words!
