### ISSUE TITLE
JwtUtils.verify and JwtUtils.sign throws NoSuchAlgorithmException for ECDSA algorithms

### ISSUE THREAD

**Issue by ibisch-dev** [jwt-scala/jwt-scala#170]
`JwtUtils.verify(Array.emptyByteArray, Array.emptyByteArray, "", ES256)`
`JwtUtils.sign(Array.emptyByteArray, "", ES256)`

_java.security.NoSuchAlgorithmException: ECDSA KeyFactory not available_

Parsing private and public keys passed as a string fails in these methods due to an incorrect algorithm name for ECDSA.
The algorithm name for creating a KeyFactory instance should be "EC", not "ECDSA" (see [Java Security Standard Algorithm Names Specification](https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#keyfactory-algorithms)).

**Comment by pauldijou** [comment]
Fixed in 5.0.0
