### ISSUE TITLE
How to decode a JWT token that is not encrypted

### ISSUE THREAD

**Issue by loicdescotte** [jwt-scala/jwt-scala#183]
Is it possible to to decode a JWT token that is not encrypted? 
My token is signed but I have no secret key and it seems mandatory to have one in the jwt-scala API.

Thanks :)

**Comment by erwan** [comment]
I haven't tried it, but did you try those?

```
JwtCirce.decode(token) // Just get the claim
JwtCirce.decodeAll(token) // Get the header, claim and signature
```

(examples with `JwtCirce` but it should work the same with others)

You can also deactivate the signature check by passing the right `JwtOptions`.

**Comment by loicdescotte** [comment]
I'm sorry, I've read to fast the API ... closing it!
Thanks for your quick answer
