### ISSUE TITLE
value jwtSession is not a member of play.api.mvc.Request

### ISSUE THREAD

**Issue by alex88** [jwt-scala/jwt-scala#19]
Hi there,

after installing play-jwt I randomly get errors like:

```
Error:(22, 13) value jwtSession is not a member of play.api.mvc.Request[A]
    request.jwtSession.getAs[User]("user") match {
            ^
```

and I've to manually reload sbt dependencies. This is my build.sbt file

```
name := "Project"
version := "0.0.1"
inConfig(Compile)(mappings in packageBin <++= Defaults.sourceMappings)
lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.7"
libraryDependencies ++= {
  val postgresV              = "9.4.1207"
  val nscalaTimeV            = "2.6.0"
  val playSlickV             = "1.1.1"
  val slickPgV               = "0.10.2"
  val slickJodaMapperVersion = "2.1.0"

  Seq(
    cache,
    ws,
    specs2 % Test,
    "org.postgresql"              %  "postgresql"                           % postgresV,
    "com.github.tminglei"         %% "slick-pg"                             % slickPgV,
    "com.github.tminglei"         %% "slick-pg_play-json"                   % slickPgV,
    "com.typesafe.play"           %% "play-slick"                           % playSlickV,
    "com.typesafe.play"           %% "play-slick-evolutions"                % playSlickV,
    "com.github.nscala-time"      %% "nscala-time"                          % nscalaTimeV,
    "com.github.tototoshi"        %% "slick-joda-mapper"                    % slickJodaMapperVersion,
    "de.svenkubiak"               % "jBCrypt"                               % "0.4.1",
    "com.pauldijou"               %% "jwt-play"                             % "0.5.1",
    "com.amazonaws"               % "aws-java-sdk"                          % "1.10.64"
  )
}

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

// Play provides two styles of routers, one expects its actions to be injected, the
// other, legacy style, accesses its actions statically.
routesGenerator := InjectedRoutesGenerator

// Newrelic configuration
enablePlugins(NewRelic)
newrelicVersion := "3.27.0"
newrelicAppName := "Project"

// Enable filters (to use CORS filter
libraryDependencies += filters
```

Everything seems correct, I've not idea on what could cause that.

**Comment by pauldijou** [comment]
Play 2.4? Compile time error? Did you checked the import to be sure to have all needed implicits in the scope? Try `import pdi.jwt._`.

**Comment by alex88** [comment]
Yeah sorry, Play 2.4, compile time errors.

Btw I already had that, this is the file that gets that jwtSession error:

``` scala
package controllers

import scala.concurrent.Future
import play.api.libs.concurrent.Execution.Implicits._

import play.api.mvc._
import play.api.mvc.Results._
import play.api.libs.json._

import pdi.jwt._

import models.User

class AuthenticatedRequest[A](val user: User, request: Request[A]) extends WrappedRequest[A](request)

trait Secured {
  def Authenticated = AuthenticatedAction
}

object AuthenticatedAction extends ActionBuilder[AuthenticatedRequest] {
  def invokeBlock[A](request: Request[A], block: AuthenticatedRequest[A] => Future[Result]) =
    request.jwtSession.getAs[User]("user") match {
      case Some(user) => block(new AuthenticatedRequest(user, request)).map(_.refreshJwtSession(request))
      case _ => Future.successful(Unauthorized)
    }
}
```

**Comment by pauldijou** [comment]
By `randomly`, do you mean it works sometime? Your code looks just fine... not sure what I can do about potential SBT problems... There is no reason for code which compile not to compile anymore if nothing changed.

Did you tried to reproduce with the `play-angular-standalone` application inside this repo? You could downgrade it to Play 2.4 and JWT Scala 0.5.1 and try to add your own stuff until it breaks.

**Comment by alex88** [comment]
I mean that sometimes it doesn't work on intellij startup, after one or two SBT refresh it works fine, And I'm having this issue since I've added jwt-play. I'll do that way when I've some free time, I'll close this for now. Thank you

**Comment by bennythomps** [comment]
I'm still having this issue. It is indeed intermittent and it's not an issue with SBT compiling it's IntelliJ. It works when building with sbt command line, but not when built with IntelliJ. It must have something going on with implicits.

**Comment by petetnt** [comment]
I was having this issue with IntelliJ too, so I decided to test it out with [Ensime](http://ensime.github.io/) on various other editors and the same issue persists and replicates on other IDEs and Text Editors (such as Atom).

Not really sure what is the issue here is either so I can't sadly help with that.

**Comment by pauldijou** [comment]
But does the project compile and works fine using SBT cli?

**Comment by petetnt** [comment]
@pauldijou yeah, it compiles just fine and the example application does work.

**Comment by shafiquejamal** [comment]
Hello, I'm having the same problem. My application compiles fine using SBT, but IntelliJ IDEA shows errors when calling the .jtwSession method on the request object. 

This is also the case with the play-angular-standalone project. I downloaded this project and imported it into IntelliJ IDEA, and there too IDEA does not recognize the .jwtSession method on the request object, even thought SBT compiles and runs the project without problems.

Has anyone found a solution for this yet? Thanks,

**Comment by yahortsaryk** [comment]
+1 Have the same issue in Intellij IDEA... The code compiles via command line by "sbt compile" but in IDE it throws compiling errors...


***UPDATE***: I fixed it by adding "JwtPlayImplicits" trait (https://github.com/pauldijou/jwt-scala/blob/master/play/src/main/scala/JwtPlayImplicits.scala) for actions and my project started to compile in IntelliJ IDEA also

**Comment by binkabir** [comment]
Hi @pauldijou Im having this same error with play 2.5.13.

**Comment by binkabir** [comment]
Interestingly, 
`import pdi.jwt.JwtSession._`
fixed the issue

**Comment by pauldijou** [comment]
If using 0.12.x, that's because all implicits have been moved inside their respective object. See [changelog](https://github.com/pauldijou/jwt-scala/blob/master/CHANGELOG.md)

**Comment by jdelafon** [comment]
I do not understand that change. I never create a `JwtJson` object, I just want to do `request.jwtSession`, what sort of implicit should I import now? I tried the suggestions above without success.
