### ISSUE TITLE
Support an option for leeway when validating with JwtTime

### ISSUE THREAD

**Issue by wuservices** [jwt-scala/jwt-scala#20]
The spec mentions that "Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew."
https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.4

Could there be an option to pass in seconds of leeway when validating exp and nbf?

**Comment by pauldijou** [comment]
As always, trying to figure a solution with the current API before adding new stuff. Is there a difference between adding 1min leeway compared to adding 1min to your session duration? As I see it in the spec, this leeway is implementation specific and internal, not accessible to users.

**Comment by wuservices** [comment]
I only saw brief mention of this in the spec in 2 places.  For servers, my assumption is that the clocks will be very close. I'm allowing some leeway to account for client clock skew so that clients can eagerly renew their sessions to save a round trip in getting a rejected request. My tokens also happen to be issued by another app service, however I could definitely change the expiration there. 

I'd say this would be a nice to have but no means not a deal breaker. If added I think it would be an optional thing as I could say many people wanting exact time validation.

**Comment by pauldijou** [comment]
Added in 0.7.1
