### ISSUE TITLE
maxAge is in second

### ISSUE THREAD

**Issue by khanetor** [jwt-scala/jwt-scala#21]
This is a block of code with comment from Play template

``` hocoon
play.http {
    session {
        # Sets the max-age field of the cookie to 5 minutes.
        # maxAge = 300
    }
}
```

So the unit of `maxAge` is in seconds. However, in your code `jwt-scala/play/src/main/scala/JwtSession.scala` where you get the max age, you assume that `maxAge` is in milliseconds, and divide it by 1000.

``` scala
val MAX_AGE: Option[Long] = getConfigMillis("play.http.session.maxAge").map(_ / 1000)
```

Is there any reason you treat `maxAge` as milliseconds, because it is standard that `maxAge` is specified in seconds. This will also affect other part of the Play application where normal session is involved, because the time for those session has been increased by **1000** times.

**Comment by pauldijou** [comment]
I think `maxAge` also accepts `Duration` syntax. But in case of a number, it converts it to seconds. I don't assume anything and I'm using `getConfigMillis` which will read a duration as milliseconds from the config file. Did the session expired way later than planned in your project?

**Comment by khanetor** [comment]
What happened for me was that I set the `maxAge = 300`, which is supposed to be 300 seconds, or 5 minutes. However, due to the `_ / 1000` part, the `MAX_AGE` is **zero** from `300 / 1000`. This makes the JWT expire instantly. I will try out the duration format later. 😄

**Comment by pauldijou** [comment]
Please, take a look at https://www.playframework.com/documentation/2.5.x/Migration23#Session-timeouts

You should either use a duration or multiply by 1000. Are you still using Play 2.3 or lower?

**Comment by khanetor** [comment]
No, I am using Play 2.5.1

**Comment by pauldijou** [comment]
The comments might be legacy. You could test if the session cookie expiration is 300ms or 300s later. It should be 300ms, just like the JWT token. If that the case, are you okay with using the new syntax or a bigger number?

**Comment by khanetor** [comment]
I will. Once I do that, I will feedback on this thread :). I am being stuck with some other tasks at the moment. I appreciate your work here ;)

**Comment by pauldijou** [comment]
Ok, closing for now but feel free to update.
