### ISSUE TITLE
Does release 4.0.0 support java 1.8 ? 

### ISSUE THREAD

**Issue by ravinderpayal** [jwt-scala/jwt-scala#211]
On google cloud the sbt community build image is based JDK 1.8
Build happens fine, but during run time we are getting this error:

"play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.UnsupportedClassVersionError: pdi/jwt/JwtArrayUtils has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0]
" 

A relevant issue about release 3.0.0, but seems it;s fixed in 3.0.1, not sure how it got reintroduced in 4.0.0.
 https://github.com/jwt-scala/jwt-scala/issues/128

**Comment by erwan** [comment]
Yes, Java 1.8 is supposed to be supported. The fix that was done is still there: https://github.com/jwt-scala/jwt-scala/blob/master/build.sbt#L97

I'll take a look, this line might not be enough.

**Comment by erwan** [comment]
That might do it: https://github.com/jwt-scala/jwt-scala/pull/212/files

Do you have a way to check if that's enough to fix Java 8 compatibility? (publish it locally using JDK11 and import in a Java 8 project)

**Comment by ravinderpayal** [comment]
Actually, I don't have a way. Did you mean to ask package a jar and use that jar? Btw I am using v4.0.0 published on mvn central repo.

**Comment by erwan** [comment]
Yes. Published versions are not going to change, but if there is an issue with recent versions to ensure compatibility with Java 8 we can fix it so future versions don't have the issue.

Did you try the latest version? The major changed because of minor changes in the signatures but it's very minor so it should be easy to adapt.

**Comment by erwan** [comment]
If you can confirm that the latest version has an issue with Java 8, I'll take a look.

**Comment by ravinderpayal** [comment]
Weirdly issue comes in when running on google cloud, locally it's working fine Java 1.8

**Comment by erwan** [comment]
hey I'm going to close for now, let me know if you find any issue with Java 1.8 on regular environments
