### ISSUE TITLE
Version for Scala 3.0.0-RC2 not published on maven

### ISSUE THREAD

**Issue by realvictorprm** [jwt-scala/jwt-scala#214]
Hi, maybe I missed something but according your release notes the latest version of the library is compatible with Scala 3.0.0-RC2 and should be published but so far I see it isn't :see_no_evil:

**Comment by erwan** [comment]
It's there: https://search.maven.org/artifact/com.github.jwt-scala/jwt-core_3.0.0-RC2/7.1.3/jar

But it's only for `core` and `upickle`, because AFAIK other libraries don't have released a stable version based on Scala 3. What json library are you using?

**Comment by realvictorprm** [comment]
I see, well we're using circe over here. I think there are preview versions of circe `0.14` available which support Scala 3.0.0-RC2. However I'm still myself in the process of figuring out how to migrate.

**Comment by realvictorprm** [comment]
PS: Thank you very much for the quick answer!

**Comment by erwan** [comment]
Yes, I'm not planning to release a version based on a pre-release (that would have to be a pre-release itself...)

So in the meantime you can include jwt-circe with `withDottyCompat`. That would pull the Scala 2.13 version but it should work with Scala 3.
