### ISSUE TITLE
AbstractMethodError exception when using json4s-jackson when calling decode

### ISSUE THREAD

**Issue by TOTBWF** [jwt-scala/jwt-scala#22]
Pretty much what the title says. The fix is super easy, just add useBigDecimalForDouble = false to the call to jparse

**Comment by pauldijou** [comment]
This is problematic, all my tests are green and should cover all decode methods. Any chance you can submit a way to reproduce the problem? Either a small project on GitHub or a PR adding a failing test to jwt-scala? You can run the Json4s Jackson tests by launching SBT and then running `json4sJacksonEdge/test`. You will probably have a `LinkageError` the 1st time, just run the command again.

**Comment by TOTBWF** [comment]
It turns out I was using an outdated version of json4s, the issue doesn't manifest itself in the current version.
