### ISSUE TITLE
JwtJsonCommon in jar

### ISSUE THREAD

**Issue by etaty** [jwt-scala/jwt-scala#23]
Would be nice to have just JwtJsonCommon exported in a jar instead of having to pick a json lib (and having the json lib version blocked ...)

jwt-json-common ?

**Comment by pauldijou** [comment]
Is this what you want?

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.pauldijou%22%20AND%20a%3A%22jwt-json-common_2.11%22

**Comment by etaty** [comment]
yep thanks 👍
