### ISSUE TITLE
Why is validateTiming in seconds?

### ISSUE THREAD

**Issue by vjames19** [jwt-scala/jwt-scala#24]
I think its natural to specify "exp" and "notBefore" fields as milliseconds since the epoch.

Is there a specific reason as to why seconds are being used?

**Comment by pauldijou** [comment]
I know... I actually implemented it in milliseconds at first but all the [JWT spec](https://tools.ietf.org/html/rfc7519#page-6) uses seconds, so it seems fair for any JWT lib to do the same.

**Comment by vjames19** [comment]
@pauldijou Thanks for you answer. Would it make sense to make this a configurable part of the library? If so, would you accept a PR with the change?

**Comment by pauldijou** [comment]
There will be no global config, so you would need to specify the millisecond option at every call to the lib. Not sure it's worth it compared to a division by 1000. What would be the benefit of such option for you?
