### ISSUE TITLE
Subject with dashes are decoded as None

### ISSUE THREAD

**Issue by barbaramcinnes** [jwt-scala/jwt-scala#250]
PR to show this: https://github.com/jwt-scala/jwt-scala/pull/249

Regex for subject doesn't include dashes, and if dashes are included, the decoded subject is None.  

There are examples in your tests using uuid subjects, but they would not pass this decoding.  Small fix, that would help me (we have some negative principal ids that fail because of this).  Thanks!

**Comment by erwan** [comment]
thanks, I'll take a look!

**Comment by erwan** [comment]
that's fixed in v8.0.2
