### ISSUE TITLE
jwt-play-json: Reads failures from unexpected values surface as NoSuchElementException and lose initial root cause

### ISSUE THREAD

**Issue by kwinter-disney** [jwt-scala/jwt-scala#278]
If the expected claims can't be parsed, the initial JsError from JwtJsonImplicits is lost, and the caller receives `Failure(java.util.NoSuchElementException: JsError.get)`

Example:
```
import pdi.jwt.{JwtJson, JwtAlgorithm, JwtJsonImplicits}
import play.api.libs.json.Json

val claim = Json.obj(("sub", 1))  // number instead of string
val token = JwtJson.encode(claim)

JwtJson.decode(token)
JwtJson.decodeJson(token)
```

I believe this is due to calling `.get` after reading, such as `jwtPlayJsonClaimReader.reads(Json.parse(claim)).get` - rather than turning the JsError into an Exception/Failure that propagates the path and "error.expected.string"

Could be something like one of these:
- `jwtPlayJsonClaimReader.reads(Json.parse(claimString)).recoverTotal(e => throw new Exception("Failed to parse claims: " + JsError.toFlatForm(e).mkString))`
  - `java.lang.Exception: Failed to parse claims: (obj.sub,List(JsonValidationError(List(error.expected.string),List())))`
- `jwtPlayJsonClaimReader.reads(Json.parse(claimString)).recoverTotal(e => throw new Exception("Failed to parse claims: " + JsError.toJson(e).toString()))`
  - `java.lang.Exception: Failed to parse claims: {"obj.sub":[{"msg":["error.expected.string"],"args":[]}]}`

**Comment by erwan** [comment]
thank you for the report, I'll take a look!

**Comment by erwan** [comment]
OK, it seems that the main issue is Play Json not returning any meaningful exception when doing a `JsResult.get`.

https://github.com/playframework/play-json/blob/main/play-json/shared/src/main/scala/play/api/libs/json/JsResult.scala#L53

I'll try to wrap that in a custom error type that gives more details.

**Comment by erwan** [comment]
Hi @kwinter-disney ,

Here is a fix: https://github.com/jwt-scala/jwt-scala/pull/281

Would that work for you? (Check the tests to see the kind of exception that will be thrown)

**Comment by kwinter-disney** [comment]
looks great!  that was quick, thanks!

looks like JwtSession might benefit from the same thing (or perhaps could delegate to JwtJson): https://github.com/jwt-scala/jwt-scala/blob/master/play/src/main/scala/JwtSession.scala#L64

**Comment by erwan** [comment]
yes good point, I'll fix it too
