### ISSUE TITLE
Why do we have different names for algorithms?

### ISSUE THREAD

**Issue by khanetor** [jwt-scala/jwt-scala#31]
You are using names for algorithms like: `[HmacMD5, HmacSHA1, HmacSHA224, HmacSHA256, HmacSHA384, HmacSHA512]`, and by default you are using `HmacSHA256`.

When I take a token generated by default to another server, written in a different language, it could not recognize the algorithm `HmacSHA256`. I then have to update the config to use `HS256` or `HS512`.

I am wondering why you have extra names. They seems to be not official names.

**Comment by pauldijou** [comment]
I couldn't find an official list for algorithm names so it's true that it's kind of arbitrary. Is there one somewhere? Maybe I should remove duplicate names if it simplifies interoperability.

**Comment by khanetor** [comment]
You can find them here https://jwt.io

Here is the list for you: 
- HS256
- HS384
- HS512
- RS256
- RS384
- RS512
- ES256
- ES384
- ES512

Your library is actually featured on this page ;)

**Comment by pauldijou** [comment]
Okay, I also found that : https://tools.ietf.org/html/rfc7518#section-3.1

Will try to find so time to fix that but probably not before a few days.

**Comment by pauldijou** [comment]
Fixed in 0.9.0. Reopen if I missed something.

**Comment by khanetor** [comment]
Awesome!
