### ISSUE TITLE
The Issuer needs to be able to extract the URI.

### ISSUE THREAD

**Issue by giiita** [jwt-scala/jwt-scala#337]
According to the RFC, it seems that Issuer can handle arbitrary strings, but Issuer's Extractor can only handle arbitrary alphanumeric characters.

https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1
https://github.com/jwt-scala/jwt-scala/blob/master/core/src/main/scala/Jwt.scala#L32

**Comment by erwan** [comment]
Yes the "core" lib has the advantage of having no dependencies but it is based on a very naive parser, if you hit an issue the best is to pick a json library (if you already use one, just pick the same) and use that one instead.

You wouldn't have this issue.
