### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by vaclavsvejcar** [jwt-scala/jwt-scala#37]
Hi Paul,
thanks for great library! Can you please also add support and release for Scala 2.12?

**Comment by pauldijou** [comment]
I wanted to do it last weekend but Play does not support 2.12 yet and I didn't have time to dive into my SBT build. So either I will find some time at some point, or wait for Play framework, or a nice PR will pop out.

**Comment by pauldijou** [comment]
I gave it a try just now and pushed the resulting work but I couldn't find a way to properly isolate Play framework projects. Every single time I try to publish, SBT will try to build them using Scala 2.12. So frustrating as all other projects compile just fine and all tests are green...

**Comment by vaclavsvejcar** [comment]
The truth is that I've completely forgotten about the Play dependency in your library. Maybe the easier way will be just wait till Play is be released for 2.12. Version 2.5.10 has been released few days ago, however, still no 2.12 support. I'll try to research the current state of Play 2.5.x for Scala 2.12. Anyway, thanks for your effort.

**Comment by vaclavsvejcar** [comment]
So according to the [discussion](https://www.reddit.com/r/scala/comments/5goowi/scala_2121_is_now_available/daum1t7/) I initiated on [r/scala](https://www.reddit.com/r/scala/) it seems that there won't be any 2.12 support for 2.5.x Play Framework and 2.6.0 _ETA_ is March-April 2017 (source: [Play Framework Roadmap](https://docs.google.com/document/d/11sVi1-REAIDFVHvwBrfRt1uXkBzROHQYgmcZNGJtDnA/pub)).

**Comment by ngbinh** [comment]
it's suck that this is the only thing blocking us from upgrading to 2.12 now.

**Comment by daniel-harrison** [comment]
I was able to get this building for 2.12 as made the mistake of moving things to 2.12 chasing the rabbit.  Had to use snapshot deps but it seems odd that play ETA won't be out for months and no 2.12, J.  I'm "only" using the jwt-json4s-jackson libraries.  Is there any way this could be decoupled from play maybe or is this an architectural desire?

**Comment by pauldijou** [comment]
@daniel-harrison It is fully decoupled actually, like 100%. I'm just having troubles with SBT. It looks like as soon as I enable cross-compilation, it will cross compile all projects with the same Scala versions even if they are different in their respective settings. I don't understand at all...

As we can see [here](https://github.com/pauldijou/jwt-scala/blob/master/build.sbt#L108-L123), I only enable 2.12 for some projects and not the Play ones. But still, trying to compile Play in 2.12

Right now, I'm considering dropping Play support from the project (already published versions will stay on Maven obviously) and putting it back when they support Scala 2.12.

**Comment by jurisk** [comment]
>  dropping Play support from the project and putting it back when they support Scala 2.12

This seems as a pragmatic solution.

**Comment by trbngr** [comment]
This bit me the other day so I just compiled everything but play for 2.12.

you can use my version until paul releases his.

`resolvers += "caliberweb repo" at "https://s3-us-west-2.amazonaws.com/repo.caliberweb.com/release"`

and `"com.pauldijou" %% s"jwt-core" % "0.10.0"`

**Comment by daniel-harrison** [comment]
@pauldijou Cool decoupled, I'm with @jurisk voting to drop play till they support; as would prefer to be on a supported 2.12 branch.  Thanks for the library BTW, did everything advertised and apart from 2.12 ;) worked great.

**Comment by pauldijou** [comment]
Done in 0.10.0

**Comment by vaclavsvejcar** [comment]
Hi @pauldijou , just for your info, Play Framework team just released milestone version of Play 2.6 for Scala 2.12

- https://mvnrepository.com/artifact/com.typesafe.play/play_2.12/2.6.0-M1
- https://www.playframework.com/documentation/2.6.0-M1/Migration26

**Comment by pauldijou** [comment]
Play support is back in 0.11.0

**Comment by vaclavsvejcar** [comment]
cool, thank you 👍

**Comment by pauldijou** [comment]
Hey folks, if any of you have too much free time, I'm looking for feedback on this PR : https://github.com/pauldijou/jwt-scala/pull/45
