### ISSUE TITLE
Wrong version in docs

### ISSUE THREAD

**Issue by bauerei** [jwt-scala/jwt-scala#390]
Hey there,

just a small thing: In the docs, the snippets for adding jwt-scala as sbt dependency contain 9.0.6 as version. When I copied the line my build failed and I realized 9.0.5 is the latest version (...or I missed something).

Running `sbt ~docs/makeMicrosite` locally renders 9.0.5 correctly.

**Comment by erwan** [comment]
Hey,

Thank you for the report! I've just released v9.0.6 so now the doc is correct.

**Comment by bauerei** [comment]
Glad to hear. Thanks :slightly_smiling_face:
