### ISSUE TITLE
Extract Audience while decoding into JwtClaim

### ISSUE THREAD

**Issue by jeet23** [jwt-scala/jwt-scala#397]
While parsing claim in the `decode`  API, there is a [function](https://github.com/jwt-scala/jwt-scala/blob/43ae11f7947ddf1d461d92768816d6defa78b1a6/core/src/main/scala/Jwt.scala#L93) called `parseClaim`.

In this function, the `aud` field is not extracted. As a result, client will be unable to identify the `aud` field in a decoded JwtClaim.
 
Something like this can be added:
```
val claim = """{"aud":"audience", "user":"some_user"}"""
val extractAudienceRegex = "\"aud\" *: *\"([\\-a-zA-Z0-9]*)\"".r
def extractAudience(claim: String): Option[String] = (extractAudienceRegex.findFirstMatchIn(claim)).map(_.group(1))

println(extractAudience(claim)) // Output: Some(audience)

```

**Comment by erwan** [comment]
Hey @jeet23 ,

Thank you for the report, feel free to make a PR!

**Comment by jeet23** [comment]
Ok, I found that there is **JwtCirce** support and it is the recommend way to use the JSON fields.
I will go ahead with that for now.

**Comment by erwan** [comment]
Good! I'll close this ticket then
