### ISSUE TITLE
Release artifact to some public repo

### ISSUE THREAD

**Issue by alari** [jwt-scala/jwt-scala#4]
I'd like to use play-json implementation of jwt, but don't want to build it myself.

Could you release an artifact somewhere, say, on sonatype repo?

**Comment by pauldijou** [comment]
Sorry, I was travelling lately. I will try to do it in the next few days.

**Comment by pauldijou** [comment]
Sorry, it was done since a few days but I wanted to finish writing and publishing docs, samples and scaladoc. All (nearly) good now.

**Comment by alari** [comment]
Thanks! :)

**Comment by alari** [comment]
The last version here is 0.0.5: http://jcenter.bintray.com/pdi/jwt-play_2.11/

Is the last version on the way now?

**Comment by pauldijou** [comment]
Sorry about that, looks like something when wrong somewhere at some point during the release process and I didn't catch it. It's fixed now.
