### ISSUE TITLE
Multiple pdi.jwt objects clash in IntelliJ

### ISSUE THREAD

**Issue by mvh77** [jwt-scala/jwt-scala#44]
Hi,

I can't get the play-angular-standalone to work with IntelliJ without tricks, there's an issue importing pdi.jwt._ since there's one of those package objects in each project. Would it make more sense to have different packages in each module?

**Comment by pauldijou** [comment]
Please give feedback about this PR which would solve your problem : https://github.com/pauldijou/jwt-scala/pull/45

**Comment by pauldijou** [comment]
Please, try 0.12.0 and close if it solves your problem.
