### ISSUE TITLE
Parsing function is (too much ?) strict

### ISSUE THREAD

**Issue by gbossert** [jwt-scala/jwt-scala#48]
A set of REGEX is used to parse JWT token header attributes such as the algorithm:

```
private val extractAlgorithmRegex = "\"alg\":\"([a-zA-Z0-9]+)\"".r
```

In my case, the JWT token is produced by a python library that generates the following header: 

```
{"alg": "RS256", "typ": "JWT"}
```

In such case, jwt-scala fails to parse our token due to spaces that are added in the string.
My question, is "should I force JWT libraries to produce tokens without spaces or should we 1) improve the regex or 2) use a json unmarshaler before checking the header ?

**Comment by pauldijou** [comment]
We can improve the regex.

**Comment by pauldijou** [comment]
Done in 0.12.1
