### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by guizmaii** [jwt-scala/jwt-scala#494]
Hi @erwan,

I'm hitting this issue https://github.com/jwt-scala/jwt-scala/pull/485 which is fixed in `master`

Would it be possible for you to release a new version maybe, please?

Thanks 🙂
Jules

**Comment by erwan** [comment]
OK, I'll do that!

**Comment by erwan** [comment]
just released: https://github.com/jwt-scala/jwt-scala/releases/tag/v9.4.1

**Comment by guizmaii** [comment]
Thanks @erwan!
