### ISSUE TITLE
Play JwtSession is incompatible with akka-http

### ISSUE THREAD

**Issue by MxFr** [jwt-scala/jwt-scala#50]
I recently switched a application form Play 2.5 to the Play 2.6 Milestone and noticed that the Session broke in the process.

After some digging I found that akka-http declares the Authorization header as a request header, which means it is filtered out in responses. So the client does not receive the JWT Token and cannot send the updated Authorization header.

I switched from the Authorization header to a custom JWT-Auth header, but now the client has to send it's JWT Token also in the custom header.  Maybe the JwtSession.HEADER_NAME should be replaced by JwtSession.REQUEST_HEADER_NAME and JwtSession.RESPONSE_HEADER_NAME, so you can use a custom header in the responses.

**Comment by pauldijou** [comment]
We could do that but before, what is the problem with only using the custom header for both requests and responses?

Also, the default behavior is to put the token inside a header of the response but feel free to put it in the body if you prefer. Just use `session.serialize` to get the signed token.

I don't really like having 2 different headers for the same feature. I would rather use the same one for both (either Authorization or a custom one) or use the header only in requests and return the token in the body of the login for example (but this might be a problem if you have a session timeout).

**Comment by MxFr** [comment]
I was under the impression that the use of the Authorization-Header is a kind of standard for submitting JWT-Tokens to the server. Perhaps a note in the documentation is sufficient to make people aware of this problem.

**Comment by pauldijou** [comment]
It is a standard but mostly because other methods, like basic authentication, are also using it. Nothing is mandatory as far as I know. If you are building an API just for your own app, it's no problem at all. If it's for a public API, I would be better to use this header but, again, as long as you write a good documentation, you are free to do whatever you want. Also, nothing forces you to use a header to return the JWT token.
