### ISSUE TITLE
Play 3.x support for `jwt-play`

### ISSUE THREAD

**Issue by b-eyselein** [jwt-scala/jwt-scala#552]
I'm trying to upgrade some of my Play Framework projects version 3.0.0. When I use the "official" Play Json version of this library (`jwt-play-json`) it works, but the "easier" version `jwt-play` currently depends on Play 2.9.0 and therefore translitively on an older version of `scala-xml` (1.3.1 or 1.2.0), while the new play version uses 2.2.0 and this results in a dependency conflict.

I'd suggest updating the Play version, but the new version changed the `groupId` from "com.typesafe.play" to "org.playframework" which might break older versions. Is there anything that can be done about that?

**Comment by erwan** [comment]
Should be done in v9.5.5 now

**Comment by b-eyselein** [comment]
Thanks :+1:
