### ISSUE TITLE
Code samples on gh-pages are unreadable (rendered without line breaks)

### ISSUE THREAD

**Issue by mturley** [jwt-scala/jwt-scala#59]
Hi there, thanks for your great library!  This is not an actual issue with your source, just something I wanted to point out is a little bit frustrating with the documentation.

On your Samples pages, (e.g. http://pauldijou.fr/jwt-scala/samples/jwt-core/) the code snippets are strangely rendered with no line breaks, appearing on the page as a single very-long line that I have to scroll horizontally to read.  I had to copy-paste and transform these samples in order to read and use them.  I'm guessing this was not intentional, maybe some regression when changing how the pages were rendered at some point?  Just a little something that you might want to look into :)

**Comment by pauldijou** [comment]
Good catch, total regression indeed. Will fix ASAP.
