### ISSUE TITLE
Release artifact to maven central

### ISSUE THREAD

**Issue by francisdb** [jwt-scala/jwt-scala#6]
Title says it all, same as #4 but with maven central.

**Comment by pauldijou** [comment]
On it, just asked Sonatype to add it ([JIRA issue](https://issues.sonatype.org/browse/OSSRH-16071))

I'm curious, why isn't Bintray and JCenter not enough?

**Comment by francisdb** [comment]
Some companies allow only maven central. Depending on anything else in your build is a higher risk of builds faling later because of missing repos/artifacts.

**Comment by pauldijou** [comment]
It should be good... It still doesn't appear when searching in the central repository but the artifacts have been released ([here](https://oss.sonatype.org/content/groups/public/com/pauldijou/)). You can now add the dependency by doing something like:

``` scala
libraryDependencies ++= Seq(
  "com.pauldijou" %% "jwt-play" % "0.3.0"
)
```

Enjoy

**Comment by francisdb** [comment]
that was fast, thanks :+1:
