### ISSUE TITLE
java.security.spec.InvalidKeySpecException: encoded key spec not recognized: Bad sequence size: 3

### ISSUE THREAD

**Issue by yatharthsharma** [jwt-scala/jwt-scala#63]
Hi, 

I am trying to validate jwt token for azure ad. I have the public key as below:

`val pubkey= "-----BEGIN CERTIFICATE-----\nMIIDBTCCAe2gAwIBAgIQZSAeaqWig4BHC1ksmNNcgjANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTE3MDUwNjAwMDAwMFoXDTE5MDUwNzAwMDAwMFowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJL7dVZkeJ8JDTPIzFNMJo9oEkvDc52zrdqWSOmex0E/3rBe1tfRmUe2O9l6NYuc10QzPaNxnkyIwa5698suNUPxGlEOwvm/h5oPeFcuxAWcgYYv5s589HWFrNjCF8EfOjZ4vU5oE1744EzxdmBiaGbeE8HDBXn1vK4owlcjawgQNF7KQ6LjSWr7xtARDF2IoKE4RYy0V0uVN4eAQ3zWRWWUt3cpYjTl34EZ9pO6CE8/If7noj75g0RYd/AHkIMdXBC4SlnNz+boLbba2ksIB+5z9jVILjvZwqx7i+k2filqZkVmasB/o2ChUFbdwg6c8DTOlyS/qB25dcfoCN2GF+cCAwEAAaMhMB8wHQYDVR0OBBYEFGKpXQNrF5IoxS6bL4F92+gxOJlIMA0GCSqGSIb3DQEBCwUAA4IBAQA3HgW5SoHlvvQVxqqi+mtscDZLhNfe13iG/nx8Er5il82b79RVydNs+f9sYxc4T4ctnrZu7x5e7jInJedNdAlrPorBdw+SfvKJsmiNndXugMew1FlcQTQVIFDCbziaJav8rKyMxPfeKkc1aixbajWZkKg6OPmmJn2ceTocbn8PMQy20xNvcWUwgF5FZZIuPqu6feOLJcUIYw+0JFZ265xka30QXpmytcIxajIzpD4PRdCIBuVSqgXacAs4t4+w+OhnosD72yvXck8M4GwX1j+vcuyw0yhDGNMmqsHWP7H3jnJiGDrKhhdVyplzDhTfv2Whbv/dIDn+meLE3yyC5yGL\n-----END CERTIFICATE-----"
`
when I try to validate the token using  Jwt.validate(token,pubkey, Seq(JwtAlgorithm.RS256))
I get the following stacktrace

```

java.security.spec.InvalidKeySpecException: encoded key spec not recognized: Bad sequence size: 3
  at org.bouncycastle.jcajce.provider.asymmetric.util.BaseKeyFactorySpi.engineGeneratePublic(Unknown Source)
  at org.bouncycastle.jcajce.provider.asymmetric.rsa.KeyFactorySpi.engineGeneratePublic(Unknown Source)
  at java.security.KeyFactory.generatePublic(KeyFactory.java:328)
  at pdi.jwt.JwtUtils$.parsePublicKey(JwtUtils.scala:114)
  at pdi.jwt.JwtUtils$.verify(JwtUtils.scala:187)
  at pdi.jwt.JwtCore$$anonfun$validate$2.apply(Jwt.scala:654)
  at pdi.jwt.JwtCore$$anonfun$validate$2.apply(Jwt.scala:653)
  at pdi.jwt.JwtCore$class.validate(Jwt.scala:636)
  at pdi.jwt.Jwt$.validate(Jwt.scala:23)
  at pdi.jwt.JwtCore$class.validate(Jwt.scala:653)
  at pdi.jwt.Jwt$.validate(Jwt.scala:23)
  at pdi.jwt.JwtCore$class.validate(Jwt.scala:722)
  at pdi.jwt.Jwt$.validate(Jwt.scala:23)
  at pdi.jwt.JwtCore$class.validate(Jwt.scala:725)
  at pdi.jwt.Jwt$.validate(Jwt.scala:23)

```

Is there anything I am doing incorrectly?

**Comment by pauldijou** [comment]
To be honest, I don't know much about RSASSA algorithms. The only advice I can give you is trying to use a `PublicKey` or `PrivateKey` rather than a `String`, it's way better. I did [some examples](http://pauldijou.fr/jwt-scala/samples/jwt-ecdsa/) for the ECDSA algorithm.

**Comment by yatharthsharma** [comment]
Hey, It worked. I converted the string to PublicKey and it was able to validate the signature.

Is there a direct way to validate the claims or should i decode it and match the attributes?

**Comment by pauldijou** [comment]
You have [a few methods](https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/main/scala/JwtClaim.scala#L54-L56). Expiration and notBefore should already be validated.

Do you have anything else in mind?

**Comment by yatharthsharma** [comment]
This is perfect. Thanks a lot!

**Comment by camdez** [comment]
@yatharthsharma I was fighting this exact battle yesterday and never could figure out how to convert the string to a `PublicKey`; can you share any tips on that?

I eventually had to fall back to using the modulus and exponent to manually construct an `RSAPublicKeySpec`.

**Comment by kershnerd** [comment]
I need to know how to do this to.  How do I convert my publicKey as a string to PublicKey?

**Comment by dapp1990** [comment]
I struggled a lot with the same problem (**Bad sequence size: 3** ) until I saw this thread. I fail as well when I tried to map my string key to a `PublicKey` class, but as @camdez suggested, I used modulus and exponent to created directly the `RSAPublicKeySpec`

I just wanted to complement this information with the snippet I used to decode my JWT token, in case some one else is struggling with this.

```scala
import java.math.BigInteger
import java.security.KeyFactory
import java.security.spec.RSAPublicKeySpec

val stringModulusBase64 = "yourStringModulusBase64"
val stringExponentBase64 = "yourStringExponent Base64"
val stringTokenBase64 = "yourStringTokenBase64"

val kf = KeyFactory.getInstance("RSA")
val modulus = new BigInteger(1, org.apache.commons.codec.binary.Base64.decodeBase64(stringModulusBase64))
val exponent = new BigInteger(1, org.apache.commons.codec.binary.Base64.decodeBase64(stringExponentBase64))
val publicKey = kf.generatePublic(new RSAPublicKeySpec(modulus, exponent))

val result = Jwt.decodeRawAll(stringTokenBase64, publicKey, Seq(JwtAlgorithm.RS256))
```

**Comment by kjetilbk** [comment]
Hey! If anyone struggle with similar errors when trying to create a Java `PublicKey`, it might be because your public key is in the wrong form, and needs to be converted (i.e. if your public key is from Auth0).

Here's some code to convert it:


```scala
import java.io.ByteArrayInputStream
import java.security.PublicKey
import java.security.cert.CertificateFactory

val publicKey: PublicKey = CertificateFactory
      .getInstance("X.509")
      .generateCertificate(new ByteArrayInputStream(yourPublicKey.getBytes))
      .getPublicKey
```

**Comment by sagarkaniche** [comment]
@kjetilbk's solution worked for me. 

Here cert is something like "MIIDBTCCAe2gAwIBAgIQZSAeaqWig4BHC1ksmNNcgjANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQg........"

```
   def getPublicKey(cert: String) = {
      val keyBytes = Base64.decode(cert)
      CertificateFactory
        .getInstance("X.509")
        .generateCertificate(new ByteArrayInputStream(keyBytes))
        .getPublicKey
   }
```
