### ISSUE TITLE
Provide a RS256 Example with public and private key

### ISSUE THREAD

**Issue by dgouyette** [jwt-scala/jwt-scala#67]
Hello,

It would be helpful to provide an example with Jwt with RS256.

**Comment by pauldijou** [comment]
Tests are running all RSA algorithms.

1. [Create public and private keys](https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/test/scala/Fixture.scala#L73-L109)
2. [Encode](https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/test/scala/JwtSpec.scala#L11-L18) using the [private key](https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/test/scala/JwtSpec.scala#L31-L35)
3. [Validate using the public key](https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/test/scala/JwtSpec.scala#L116-L119)

You can also [generate random keys](https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/test/scala/Fixture.scala#L111-L113) and [check everything works](https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/test/scala/JwtSpec.scala#L45-L57)

Is that good enough or would you prefer a more structured example?

**Comment by perotom** [comment]
It would be awesome to have an example how to use RS256 with jwt-play sessions (is it working?) and maybe also external providers like Auth0. I am currently using HS256 with Auth0 and it works great!
I am willing to contribute some time if you need help.

**Comment by dgouyette** [comment]
I made this code to works with auth0 and playframework. May be useful for you @perotom 

```scala
def url(config: Config) = s"https://${config.domain}/.well-known/jwks.json"

  /**
    *
    * @param token a jwt token (RS256) to verify using public key
    * @return true if token is verified
    */
  def verify(token: String)(implicit config: Config): Future[Either[Unit, SignedJWT]] = {
    Try(SignedJWT.parse(token.replace("Bearer ", ""))).fold(
      _ => Future.successful(Left(())),
      signedJWT => {
        val keyId = signedJWT.getHeader.getKeyID
        for {
          jwtjsString <- loadjwtksJson(config)
        } yield {
          val publicKeys = JWKSet.parse(jwtjsString.toString())
          val rsaPublicKeyOpt = Option(publicKeys.getKeyByKeyId(keyId).asInstanceOf[RSAKey])
          val result = rsaPublicKeyOpt.map(rsa =>
            new RSASSAVerifier(rsa.toRSAPublicKey)
          ).exists(signedJWT.verify(_))
          Logger.info(s"jwt keyId = $keyId, valid = $result, token=$token")
          if (result) Right(signedJWT) else Left(())
        }
      }
    )
  }

  def getToken(code: String)(implicit req: play.api.mvc.RequestHeader, config: Config): Future[Either[JsValue, Token]] = {
    wsclient.url(s"https://${config.domain}/oauth/token")
      .withHttpHeaders(HeaderNames.ACCEPT -> MimeTypes.JSON)
      .post(Json.obj(
        "client_id" -> config.clientId,
        "client_secret" -> config.secret,
        "redirect_uri" -> config.callbackURL,
        "code" -> code,
        "grant_type" -> "authorization_code"
      ))
      .flatMap(t => t.status match {
        case 403 => Future.successful(Left(t.json))
        case 200 => Future.successful(t.json.validate[Token].asEither.fold(
          err => Left(JsError.toJson(err)),
          t => {
            Logger.info(s"access_token = ${t.access_token}")
            Logger.info(s"id_token = ${t.id_token}")
            Right(t)
          }
        ))
      }
      )
  }


  def getUser(accessToken: String)(implicit req: play.api.mvc.RequestHeader, config: Config): Future[Either[JsObject, UserAuth0]] = {
    wsclient.url(String.format(s"https://${config.domain}/userinfo"))
      .withQueryStringParameters("access_token" -> accessToken)
      .get().flatMap(response => response.json.validate[UserAuth0].fold(
      errors => Future.successful(Left(JsError.toJson(errors))),
      u => Future.successful(Right(u))
    ))
  }
```

**Comment by perotom** [comment]
@dgouyette awesome thank you!
I am currently using a custom `ActionBuilder` to authenticate the user:
```scala
request.jwtSession.claimData.asOpt[JWTToken] match {
        case Some(token) =>Future.successful(Ok)  // Valid
        case _ => Future.successful(Unauthorized) // Invalid
}
```
It would be nice if `JwtPlayImplicits` would support RS256 out of the box.

**Comment by pauldijou** [comment]
Thanks for sharing @dgouyette 

PR is welcome to support RS256. You would need to check if algorithm is symmetric or not at bootstrap and depending on that use one (HMAC) or two keys (RSASSA or ECDSA, public and private).
