### ISSUE TITLE
Ability to add own claim?

### ISSUE THREAD

**Issue by supersnager** [jwt-scala/jwt-scala#68]
Hello, 
Is it possible to add my own custom claim to JwtClaim in type safe manner?
For example i want to create claim as (added my_custom_claim property):
`{
  "iss": "issuer",
"sub": "user",
  "aud": ["service-"],
  "exp": 1506094471,
  "iat": 1506093871,
  "jti": "d82e9ff9-c996-4654-8ba0-8926d8721af6",
  "my_custom_claim" : "my custom claim value"
}
`

**Comment by pauldijou** [comment]
Depends on which implementation you are using. There is no type safety at all with the basic JWT Scala. Otherwise, it's up to the JSON lib you have chosen.

You can do `claim = claim + """{"my_custom_claim":"my custom claim value"}"""`
