### ISSUE TITLE
jwt-json4s-native and jwt-json4s-jackson are missing at maven

### ISSUE THREAD

**Issue by amutake** [jwt-scala/jwt-scala#7]
Hi. Thank you for the nice libraries.

I set up build.sbt like the following according to the readme, but the library was not found.

```
libraryDependencies ++= Seq(
  "com.pauldijou" %% "jwt-json4s-jackson" % "0.4.0"
)
```

It seems that jwt-json4s-native and jwt-json4s-jackson are not published to maven central. [search result](http://search.maven.org/#search%7Cga%7C1%7Ccom.pauldijou)

Is it possible to publish these libraries? or is there any other solution?

**Comment by pauldijou** [comment]
Good catch, thanks. There was an issue with the project build around json4s indeed. Should be fixed and released. Just have to wait a bit for Maven Central to realize it. Probably a few more hours.

**Comment by amutake** [comment]
Thank you!
