### ISSUE TITLE
Ask: How to get listAll object after addingToJwtSession

### ISSUE THREAD

**Issue by sugondonababan** [jwt-scala/jwt-scala#71]
How to get listAll object after addingToJwtSession??

**Comment by pauldijou** [comment]
What's the `listAll` object you are talking about?

**Comment by sugondonababan** [comment]
get session active

**Comment by pauldijou** [comment]
You can call  `jwtSession` on a `Request` to get the active session ([see example](https://github.com/pauldijou/jwt-scala/blob/master/examples/play-angular/app/controllers/Secured.scala#L19))
