### ISSUE TITLE
make JwtJson4s.parseClaim, JwtJson4s.parseHeader publicly accessible

### ISSUE THREAD

**Issue by evbo** [jwt-scala/jwt-scala#73]
Hi,

I am not able to use `JwtJson4s.decode()` without first getting the publicKey (since my signature is always non-empty). But in order to get the publicKey, my specific approach to using JWT involves looking up the publicKey from a database using the so-called [kid header claim](https://stackoverflow.com/a/43870513/1080804).

So, the process is:

1) decode the claims
2) check if the claims are expired (if not continue)
3) decode the header
4) get the `kid` from the decoded header
5) select the corresponding publicKey from the database based on the `kid`
6) using the publicKey, validate

This means I ended up copying and pasting the `parse` boilerplate of [these protected methods](https://github.com/pauldijou/jwt-scala/blob/989f6d4a51b32bf9edff7c5dc048dc6021027802/json/json4s-jackson/src/main/scala/JwtJson4sJackson.scala#L25-L26), that way I didn't need any `key` to decode the claims:

```
val parts = token.split("\\.")
val claims = JwtJson4s.readClaim(parse(JwtBase64.decodeString(parts(1))))
val keyId = extractString(parse(JwtBase64.decodeString(parts(0))), "kid").get
```

Would it be alright to make those methods publicly accessible for this fairly common use case? Or, could there be a `decodeAll` method [that did not perform validate](https://github.com/pauldijou/jwt-scala/blob/8d3210baca2383ffb812b81e3d5c1b448fa231dd/core/common/src/main/scala/Jwt.scala#L401)?

Here is the boilerplate used above that it would help to avoid:

```
protected def parse(value: String): JObject = jparse(value) match {
    case res: JObject => res
    case _ => throw new RuntimeException(s"Couldn't parse [$value] to a JObject")
  }

  private def extractString(json: JObject, fieldName: String): Option[String] = (json \ fieldName) match {
    case JString(value) => Option(value)
    case JNull => None
    case JNothing => None
    case _ => throw new JwtNonStringException(fieldName)
  }
```

**Comment by pauldijou** [comment]
I'm not 100% sure, but those functions are `protected`, so it should mean that if you extend the object, you will have access to them and then you can freely expose them.

The idea was to only publicly expose "safe" functions which include validation. And if someone wanted to do some dangerous stuff, it would need to kind of override the default feature to allow that. That's why they are `protected` rather than `private`.

Would that work for you?

**Comment by evbo** [comment]
I like that idea, but my understanding is that Scala does not allow you to directly extend an object. But if it were a trait then I would be able to. Does that sound right to you?

https://stackoverflow.com/q/7625040/1080804

**Comment by pauldijou** [comment]
Maybe? Sorry, it's been years since I have done any Scala. One way of solving it would be to make all current `object` as `trait` and then create an empty object extending it. This way, you could also freely extend those traits in your own code if needed.

The other solution is to just make them public et let people be responsible :-)

Do you have a preference? Would you consider doing a PR? I don't really have time to code and test Scala code right now.

**Comment by evbo** [comment]
sorry I didn't get back to you on this. There is a very simple fix: just adding `Option[String]` variable to [your JwtHeader case class](https://github.com/pauldijou/jwt-scala/blob/24c2d17ca1cf9c67c60b6e7a16f5fdd1e313d53e/core/common/src/main/scala/JwtHeader.scala#L3-L37). "kid" is an optional header claim, and so it's probably best to include it.

However, I was never able to run tests. I always hit this issue:

```
java.util.NoSuchElementException: head of empty stream at com.typesafe.sbt.SbtGit
```

The PR would be simple though: 

```
case class JwtHeader(
  algorithm: Option[JwtAlgorithm] = None,
  typ: Option[String] = None,
  contentType: Option[String] = None,
  keyId: Option[String] = None
) {
  def toJson: String = JwtUtils.hashToJson(Seq(
    "typ" -> typ,
    "alg" -> algorithm.map(_.name).orElse(Option("none")),
    "cty" -> contentType
    "kid" -> keyId
  ).collect {
    case (key, Some(value)) => (key -> value)
  })

  /** Assign the kid to the header */
  def withKeyId(kid: String): JwtHeader = this.copy(kid = Option(kid))

/** Assign the type to the header */
  def withType(typ: String): JwtHeader = this.copy(typ = Option(typ))

  /** Assign the default type `JWT` to the header */
  def withType: JwtHeader = this.withType(JwtHeader.DEFAULT_TYPE)
}

object JwtHeader {
  val DEFAULT_TYPE = "JWT"

  def apply(algorithm: Option[JwtAlgorithm]): JwtHeader = algorithm match {
    case Some(algo) => JwtHeader(algo)
    case _ => new JwtHeader(None, None)
  }

  def apply(algorithm: JwtAlgorithm): JwtHeader = new JwtHeader(Option(algorithm), Option(DEFAULT_TYPE))

  def apply(algorithm: JwtAlgorithm, typ: String): JwtHeader = new JwtHeader(Option(algorithm), Option(typ))

  def apply(algorithm: JwtAlgorithm, typ: String, contentType: String): JwtHeader =
    new JwtHeader(Option(algorithm), Option(typ), Option(contentType))

def apply(algorithm: JwtAlgorithm, typ: String, contentType: String, keyId: String): JwtHeader =
    new JwtHeader(Option(algorithm), Option(typ), Option(contentType), Option(keyId))
}
```

**Comment by pauldijou** [comment]
Sure, I can do that. I don't think the error is related to the project itself btw.

**Comment by pauldijou** [comment]
Done in 0.16.0

**Comment by evbo** [comment]
@pauldijou thank you for updating that, but I've realized something in pondering jwt claims: there is a concept of private and public claims. What you have implemented are public claims. Private claims are arbitrary values that the administrator can decide for their private network.

That said, do you agree there's a pretty neat opportunity to do the following refactor:

```
trait JwtJsonCommon[J] extends JwtCore[H<:JwtHeader, C<:JwtClaim] {
```

Then, if JwtHeader and JwtClaim are both traits, it will support private and public (header) claims!

I can open this as a new issue if you like, but I thought I'd share this idea here too since it's closely related to the issue I was having.
