### ISSUE TITLE
Release of new version backed by Circe 0.9

### ISSUE THREAD

**Issue by jan0sch** [jwt-scala/jwt-scala#78]
Hi,

as the PR (https://github.com/pauldijou/jwt-scala/pull/75) has been merged could you please release the new version which uses Circe 0.9?

Thanks in advance. :-)

**Comment by pauldijou** [comment]
I cannot easily... This might sound stupid, but my computer with my PGP keys is actually in transit inside a container on a super slow boat and I will actually only get it back mi-February. I will try to find if I have a backup somewhere online over the weekend.

**Comment by jan0sch** [comment]
No worries, it takes as long as it takes. But thanks for the heads up. We'll just plan regarding that timeframe.

**Comment by yellowstonesoftware** [comment]
any news on this?

**Comment by pauldijou** [comment]
I did it this WE but failed to fully publish it, see #81 . Will try to fix this week.

**Comment by pauldijou** [comment]
Released in 0.15.0
