### ISSUE TITLE
Integration with satellizer

### ISSUE THREAD

**Issue by binkabir** [jwt-scala/jwt-scala#8]
Hi Pauldijou, 
This is  a nice library, Im trying to integrate this using angularjs satellizer library and I'm having some issues . Actually satellizer is expecting a response object with a key "token", how do I implement this ? 

Thanks.

**Comment by pauldijou** [comment]
In the [sample](https://github.com/pauldijou/jwt-scala/blob/master/examples%2Fplay-angular%2Fapp%2Fcontrollers%2FApplication.scala#L30), I am using the `addingToJwtSession` shortcut but you could put the session directly inside the body of the response. Something like:

``` scala
val session = JwtSession() + ("user", User(form._1));
Ok(Json.obj("token" -> session.serialize));
```

**Comment by binkabir** [comment]
Great, It worked nice. 

Many Thanks.
