### ISSUE TITLE
Scala.js support

### ISSUE THREAD

**Issue by alari** [jwt-scala/jwt-scala#80]
It looks like the only part of jwt-scala that can't be cross-built to Scala.js is cryptography. 
It would be awesome to keep it JDK-specific, cross build all data structures and logic, and force users of the library to implement crypto functions for JS themselves.

**Comment by pauldijou** [comment]
I will never have the time to do that, I moved away from Scala. I'm open to PR if it doesn't break too much stuff for non-Scala.js users.
