### ISSUE TITLE
Cannot decode Java 8 instant

### ISSUE THREAD

**Issue by shafiquejamal** [jwt-scala/jwt-scala#85]
Hello, 

Thanks for this great project. I am having trouble decoding a `JsObject` that contains a Java 8 `Instant`. I'm using `jwt-play-json`, and following the example here 

http://pauldijou.fr/jwt-scala/samples/jwt-play-json/

Here is code that reproduces the error:

```
scala> val claim = Json.obj(
     |         "userID" -> userDetails.userID.toString,
     |         "iat" -> time)
claim: play.api.libs.json.JsObject = {"userID":"00000000-0000-0000-0000-000000000201","iat":"2016-12-30T18:14:15Z"}

scala> val token = JwtJson.encode(claim, key, algo); JwtJson.decodeJson(token, key, Seq(JwtAlgorithm.HS256))
token: String = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySUQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAyMDEiLCJpYXQiOiIyMDE2LTEyLTMwVDE4OjE0OjE1WiJ9.0fiF9XcabbmE_jgu48fOIqn5v2sjvfyZdyUog2N1uZ8
res18: scala.util.Try[play.api.libs.json.JsObject] = Failure(java.util.NoSuchElementException: JsError.get)
```

`time` is a Java 8 instant:

```
scala> time
res20: java.time.Instant = 2016-12-30T18:14:15Z
```

Am I doing something wrong here?

Thanks,

**Comment by shafiquejamal** [comment]
I found the problem - it is the key "iat". I should choose a different key name.

**Comment by pauldijou** [comment]
Yeah, the `iat` property is defined by JWT spec as a number representing the timestamp in seconds. Either use it that way or pick another name.
