### ISSUE TITLE
jwt-play should automatically add "iat" in addition to "exp"

### ISSUE THREAD

**Issue by DrewDennison** [jwt-scala/jwt-scala#86]
The security section of your website says "you should always add an issuedAt attribute to it". I think jwt-play should automatically add `iat` and update during session refreshes.

**Comment by lediur** [comment]
While we're at it, is `nbf` worth adding to the token as well?

**Comment by pauldijou** [comment]
Not really in favour of imposing anything inside a lib most of the time. There is always that one person with a use-case where it is not needed and there is no way to remove it anymore... There is plenty of other ways to generate a different tokens without using `iat` for example, using `nbf` is one of them.

I could consider having it behind a config property enabling it if someone want to do a PR.

**Comment by fernaspiazu** [comment]
Following the [RFC-7519](https://tools.ietf.org/html/rfc7519#page-8), most of the Claims are optional. I think there's no need to add this feature.
