### ISSUE TITLE
Question about Validate

### ISSUE THREAD

**Issue by kershnerd** [jwt-scala/jwt-scala#87]
I have an access token from auth0 (RS256) that correctly validates in jwt.io.  But no matter what I try in the Jwt.validate, I always get `invalid` back.

Your docs say that the second parameter to Jwt.validate is the public or private key.  I am attempting to use the public key (because of the asymmetric nature or RS256).  

Is the public key just the public key or do I have to do an RSA256 or base64 decode/encode of the key before passing it to the validate function?

Do I need to include the `-----BEGIN CERTIFICATE-----` before and after the key?

Thanks for any information.

**Comment by pauldijou** [comment]
Did you managed to create a real Java `PublicKey` instance? For such algorithms, using raw strings is kind of hard to predict.

**Comment by fernaspiazu** [comment]
@kershnerd your PublicKey should be a `.pem`:
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBg.........................
-----END PUBLIC KEY-----
```
After that you have to create an instance of java.security.PublicKey with it.
See discussion #89 :-)
Cheers.
