### ISSUE TITLE
RS512 is not supported in PlayJwt

### ISSUE THREAD

**Issue by orkunkl** [jwt-scala/jwt-scala#89]
Hey there, I wanted to use your library in your project. In the documentation, it says RS512 is supported but I get `You can only use HMAC algorithms for [play.http.session.algorithm]` error. Isn't it implemented?

**Comment by pauldijou** [comment]
It is but Play expects symmetric algorithms for session encryption, that's why you can only use HMAC for the config file. You will probably need to use a custom way to encrypt it.

**Comment by fernaspiazu** [comment]
@orkunkl in order to use RS512 or asymmetric algorithms, it should be enough to instantiate your `java.security.PublicKey` somewhere, i.e:
```
val publicKey: PublicKey = (
  decodeBase64 andThen 
  newX509EncodedKeySpec andThen 
  keyFactory.generatePublic
)(yourPublicKeyBase64String)
```
and then:
```
Jwt.decode(jwt, publicKey, Seq(JwtAlgorithm.RS512))
```
Furthermore, you could have your PublicKey inside a file or as a string in your `application.conf`, it's enough the Base64 piece ;-)
