### ISSUE TITLE
Encryption/Decryption Support?

### ISSUE THREAD

**Issue by kevinmeredith** [jwt-scala/jwt-scala#94]
Thanks for this library!

I did not see any examples for encrypting a JWT. Is there any support in this repo for encryption/decryption of the JWT?

Thanks

**Comment by pauldijou** [comment]
What do you mean exactly? Nearly all the functions of this lib are about encrypting and decrypting JWT.

https://pauldijou.github.io/jwt-scala/samples/jwt-core

**Comment by kevinmeredith** [comment]
Hi @pauldijou - thanks for replying! In order to encrypt, i.e. not only sign, the JWT content, do I need to select one of these - https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/main/scala/JwtAlgorithm.scala#L68-L73? Thanks!

**Comment by fernaspiazu** [comment]
Maybe you can find the answer in this issue: https://github.com/pauldijou/jwt-scala/issues/89

**Comment by kevinmeredith** [comment]
Thanks, @fernaspiazu. 

So, to encrypt/decrypt the JWT, I must use public key encryption, i.e. encrypt via `Jwt#encode` : https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/main/scala/Jwt.scala#L88 and then decrypt via: `Jwt#decode` : https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/main/scala/Jwt.scala#L567?

In other words, I cannot encrypt with a `SecretKey` alone, i.e. private key encryption?

**Comment by pauldijou** [comment]
`SecretKey` is supported too: https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/main/scala/Jwt.scala#L83, but for HMAC algorithms.

If you check out [the tests](https://github.com/pauldijou/jwt-scala/blob/master/core/common/src/test/scala/Fixture.scala#L142-L225), you can see what kind of token is going to be produced depending on the type of algorithms. Depends on which one you want to use then.

**Comment by kevinmeredith** [comment]
https://en.wikipedia.org/wiki/HMAC notes

> HMAC does not encrypt the message. 

As I understand then, it signs it, but does not encrypt. Is that right, @pauldijou? 

As a result, it seems to me that I need to use asymmetric (public/private key pairs) to encrypt the JWT - HMAC isn't sufficient for my purposes, I reckon.

**Comment by kevinmeredith** [comment]
Let me give an example to demonstrate my confusion:

```scala
// using ammonite w/ version 0.14.1 of this library
@ val rsa = KeyPairGenerator.getInstance("RSA") 
rsa: KeyPairGenerator = java.security.KeyPairGenerator$Delegate@28964710

@ rsa.init 
initialize
@ rsa.initialize(512) 


@ val keyPair = rsa.gener 
generateKeyPair
@ val keyPair = rsa.generateKeyPair 
keyPair: KeyPair = java.security.KeyPair@322e3eba

@  JwtCirce.encode(JwtClaim(subject = Some("bill")).toJson, keyPair.getPri 
getPrivate
@  JwtCirce.encode(JwtClaim(subject = Some("bill")).toJson, keyPair.getPrivate, JwtAlgorithm.RS256) 
res46: String = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJiaWxsIn0.TyJZOs4nUV5YZB_SR4GFOI3C75dZvNd3aHRf0OT2W_-msNfglnPectPeb8FC5wAEGwkoZzyw6g_31njTHjXHaA"
```

Pasting the JWT into jwt.io shows its plaintext value:

![screen shot 2018-09-21 at 3 34 06 pm](https://user-images.githubusercontent.com/1967302/45902212-d418f080-bdb3-11e8-96c6-414866fe6228.png)

My naive expectation is that the JWT would be encrypted, but it doesn't appear to be, at least based on the above example.

Can you please help me to understand?

Thanks!

**Comment by fernaspiazu** [comment]
Hi @kevinmeredith 
Yes, in the case you use asymmetric algorithm (public/private key pair), the entire JWT is not encrypted but transformed in `Base64` and then **signed** with the `PrivateKey`. Then, your application (or resource server) will have to verify the validity of that JWT, and that must be achieved with the `PublicKey`.

The same idea also applies for `HMAC` (or symmetric) algorithm, with the difference that the **secret** token will be shared between Authorization server and Resource server.

Let me know if it's clear :relaxed: 

Cheers.

**Comment by kevinmeredith** [comment]
Thanks! So, it seems to me then that this issue is real then, i.e. this library does not support encrypting the JWT, no?

**Comment by fernaspiazu** [comment]
Mmm, I don't think exist any issue... If you want to encrypt your JWT somehow, you can do it, but you'll have to implement it.

This library allows you to **sign/validate** JWT with either **symmetric** or **asymmetric** algorithms.

The fact the entire JWT (I mean the entire string xxx.yyyyy.zzz) should be encrypted or not goes beyond the main goal of this library, maybe you can find further info in the IETF document: https://tools.ietf.org/html/rfc7519

Cheers :relaxed:

**Comment by pauldijou** [comment]
Thx for your answer @fernaspiazu , that's exactly it.

It's been ages since the last time I played with JWT... If you are using HTTPS, shouldn't it be fine by default? (aka encrypted)

**Comment by fernaspiazu** [comment]
Hi @pauldijou.

Yes, I forgot that detail: @kevinmeredith In HTTPS any information is encrypted, included JWT.

**Comment by ArinRayAtCornerStoneFS** [comment]
> Mmm, I don't think exist any issue... If you want to encrypt your JWT somehow, you can do it, but you'll have to implement it.
> 
> This library allows you to **sign/validate** JWT with either **symmetric** or **asymmetric** algorithms.
> 
> The fact the entire JWT (I mean the entire string xxx.yyyyy.zzz) should be encrypted or not goes beyond the main goal of this library, maybe you can find further info in the IETF document: https://tools.ietf.org/html/rfc7519
> 
> Cheers ☺️

I think the issue still stands because signing and encryption are two different modes of operation and the usage of public/private keys flips between the two.
See https://stackoverflow.com/a/60540274 for example.
