### ISSUE TITLE
Spray-json support

### ISSUE THREAD

**Issue by Slakah** [jwt-scala/jwt-scala#98]
Add [spray-json](https://github.com/spray/spray-json) support.

**Comment by pauldijou** [comment]
Sorry @Slakah , I'm not doing any Scala anymore and not really planning to learn one more JSON lib... If you do a PR, I will review it and merge. You can take inspiration how it is done for Circe for example.

**Comment by Slakah** [comment]
@pauldijou , no worries. I've created a quick PR, let me know if there are any issues with it!

Btw, thanks for taking the time to support a library for which your no longer using the programming language!
